# Generated by Django 4.2 on 2023-05-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(choices=[('Tour', 'Tour'), ('Travel', 'Travel'), ('Health', 'Health'), ('Diet', 'Diet'), ('Lifestyle', 'Lifestyle')], max_length=200, unique=True),
        ),
    ]
