# Generated by Django 4.1.4 on 2022-12-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='reached_amount',
            field=models.IntegerField(default=0),
        ),
    ]
