# Generated by Django 4.1.4 on 2022-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cause_reached_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='This is a string describing maybe the activities of the event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
