# Generated by Django 4.1.4 on 2022-12-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_description_event_number_of_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cause',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='event', to='main.cause'),
        ),
    ]
