# Generated by Django 4.1.4 on 2022-12-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cause_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=models.ImageField(upload_to='cause_images'),
        ),
    ]
