# Generated by Django 4.1.4 on 2022-12-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cause_event_date_alter_cause_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='number_of_comments',
            new_name='comment_count',
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
