# Generated by Django 4.1.4 on 2022-12-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cause_creator_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='past',
            field=models.BooleanField(default=False),
        ),
    ]
