# Generated by Django 4.1.4 on 2022-12-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
