# Generated by Django 4.1.4 on 2022-12-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cause_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='reason',
        ),
    ]
