# Generated by Django 4.1.4 on 2023-01-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-time']},
        ),
        migrations.CreateModel(
            name='EventPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pics', to='main.event')),
            ],
        ),
    ]
