# Generated by Django 4.1.4 on 2023-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentor',
            name='image',
            field=models.ImageField(blank=True, default='commentor_images/default2.jfif', upload_to='commentor_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='user_profile_pics/default3.png', null=True, upload_to='user_profile_pics'),
        ),
    ]
