# Generated by Django 4.1.4 on 2023-01-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_comment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentor',
            name='image',
            field=models.ImageField(blank=True, default='commentor_images/default.jfif', upload_to='commentor_images'),
        ),
    ]
