# Generated by Django 4.1.4 on 2023-01-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_commentor_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-creation_date']},
        ),
    ]
