# Generated by Django 4.1.5 on 2023-01-12 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_newslettermember_alter_volunteer_volunteer_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='newslettermember',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-volunteer_date']},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_bio',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='past',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentor_image',
            field=models.ImageField(blank=True, default='commentor_images/default.jfif', upload_to='commentor_images'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentor_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='newslettermember',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 19, 59, 52, 729136)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 19, 59, 52, 729136)),
        ),
        migrations.DeleteModel(
            name='Commentor',
        ),
    ]
