# Generated by Django 4.1.5 on 2023-01-14 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_newslettermember_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_date', models.DateTimeField(default=datetime.datetime(2023, 1, 14, 16, 49, 16, 60527))),
            ],
            options={
                'ordering': ['-contact_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='donator',
            name='picture',
            field=models.ImageField(null=True, upload_to='donator_images'),
        ),
        migrations.AlterField(
            model_name='newslettermember',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 16, 49, 16, 76151)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 16, 49, 16, 60527)),
        ),
    ]
