# Generated by Django 4.1.5 on 2023-01-15 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_contactor_alter_event_options_alter_donator_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactor',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 46, 41, 664216)),
        ),
        migrations.AlterField(
            model_name='donator',
            name='full_name',
            field=models.CharField(max_length=150, null=True, verbose_name='donator_name'),
        ),
        migrations.AlterField(
            model_name='newslettermember',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 46, 41, 679836)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 46, 41, 664217)),
        ),
    ]
