# Generated by Django 4.1.5 on 2023-01-15 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_contactor_contact_date_alter_donator_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactor',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 18, 37, 59, 395127)),
        ),
        migrations.AlterField(
            model_name='donator',
            name='full_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newslettermember',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 18, 37, 59, 395127)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 18, 37, 59, 395127)),
        ),
    ]
