# Generated by Django 4.1.5 on 2023-01-17 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_contactor_contact_date_alter_donator_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='event_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 17, 30, 31, 964635)),
        ),
        migrations.AlterField(
            model_name='newslettermember',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 17, 30, 31, 964636)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 17, 30, 31, 964636)),
        ),
    ]
