# Generated by Django 4.1.5 on 2023-01-17 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_cause_event_date_alter_contactor_contact_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 17, 17, 35, 24, 856521)),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 17, 35, 25, 31816)),
        ),
        migrations.AlterField(
            model_name='newslettermember',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 17, 35, 25, 39823)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 17, 35, 25, 14977)),
        ),
    ]
