# Generated by Django 4.1.5 on 2023-01-17 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_cause_event_date_alter_contactor_contact_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 17, 17, 37, 11, 306405)),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 17, 37, 11, 337647)),
        ),
        migrations.AlterField(
            model_name='newslettermember',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 17, 37, 11, 353273)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 17, 37, 11, 337648)),
        ),
    ]
