# Generated by Django 4.1.5 on 2023-01-18 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_cause_event_date_alter_contactor_contact_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='team_member_images')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2023, 1, 18, 9, 2, 8, 447852))),
            ],
        ),
        migrations.AlterField(
            model_name='cause',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 18, 9, 2, 8, 400978)),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 9, 2, 8, 432225)),
        ),
        migrations.AlterField(
            model_name='newslettermember',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 9, 2, 8, 447852)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 9, 2, 8, 432225)),
        ),
    ]
