# Generated by Django 4.1.6 on 2023-04-14 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_teammember_alter_cause_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='event_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 18, 42, 36, 221339)),
        ),
        migrations.AlterField(
            model_name='newslettermember',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 18, 42, 36, 221340)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 18, 42, 36, 221340)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 18, 42, 36, 205716)),
        ),
    ]
