# Generated by Django 4.1.6 on 2023-04-28 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_cause_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 10, 47, 19, 149838)),
        ),
    ]
