# Generated by Django 4.1.6 on 2023-04-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_cause_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
