# Generated by Django 4.2 on 2023-05-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_cause_creation_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
